<?php $count_events = count($events); ?>
<?php $week_days = 7; ?>
<?php $start_week = 19; ?>
<?php $events = _toArray($events); ?>
<?php $event = array_shift($events); ?>
<?php $event_date_time = _getDate($event->date); ?>

<?php
    function _getDate($date) {
      $date = explode(' ', $date);
      
      return [
          'date' => $date[0],
          'time' => $date[1],
      ];
    }
    
    function _toArray($objects) {
        $arr = [];
        foreach ($objects as $object) {
            $arr[] = $object;
        }
        
        return $arr;
    }
?>

<?php for ($i = 0; $i < $week_days; $i++): ?>
    <?php if ($i == 0 || $i == 4): ?>
        <div class="row m-3">
    <?php endif ?>
            <div class="col-md-3">
                <div class="card">
                    <div class="card-body">
                        <div class="card-header">
                            <?php $start_week++ ?>
                            <span class="date"><?= $start_week ?></span>
                        </div>
                        
                        <?php if ($event_date_time['date'] === "2021-07-{$start_week}"): ?>
                            <div class="info" data-toggle="modal" data-target="#event-<?= $start_week; ?>">
                                <span class="event-pin"></span>
                                <div class="event-header"><?= $event->title; ?></div>
                                <div class="event-summary"><?= $event->summary; ?></div>
                                <div class="event-date"><?= $event->date; ?></div>
                            </div>

                            <!-- Modal -->
                            <div class="modal fade" id="event-<?= $start_week; ?>" tabindex="-1" role="dialog" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        <div class="modal-body">
                                            <form method="post" action="/subscribe/">
                                                <div class="form-group">
                                                    <label for="name">ФИО</label>
                                                    <input name="name" type="text" class="form-control" id="name" placeholder="Введите ФИО">
                                                </div>
                                                <div class="form-group">
                                                    <label for="email">Email</label>
                                                    <input name="email" type="email" class="form-control" id="email" placeholder="Введите Email">
                                                </div>
                                                <input type="hidden" name="event_id" value="<?= $event->id ?>">
                                                <button type="submit" class="btn btn-primary">Subscribe</button>
                                            </form>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        
                          <?php $event = array_shift($events); ?>
                          <?php $event_date_time = _getDate($event->date); ?>
                        <?php endif ?>
                    </div>
                </div>
            </div>
    <?php if ($i == 3 || $i == 6): ?>
        </div>
    <?php endif ?>
<?php endfor; ?>

<h2>Список клиентов(для наглядности):</h2>
<?php
    foreach ($clients as $client) {
        echo '<pre>';
        echo $client->name, " " , $client->email, " ", $client->eventId . PHP_EOL;
        echo '</pre>';
    }
?>
