<?php

$title = 'Event';
$this->headTitle($title);
?>
  <h1><?= $this->escapeHtml($title) ?></h1>
<?php
/*
$form->setAttribute('action', $this->url('subscribe', ['action' => 'subscribe']));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('event_id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('email'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
*/
?>
